### ISSUE TITLE
psm['spectrum_id'] is not integer with pepxml

### ISSUE THREAD

**Issue by levitsky** [michabirklbauer/internal_ions#59]
Traceback when uploading a pepXML file:

```
Traceback (most recent call last):
  File "/home/levitsky/.pyenv/versions/3.11.10/envs/internal_ions/lib/python3.11/site-packages/streamlit/runtime/scriptrunner/script_runner.py", line 600, in _run_script
    exec(code, module.__dict__)
  File "/home/levitsky/work/internal_ions/streamlit_app.py", line 200, in <module>
    main()
  File "/home/levitsky/work/internal_ions/streamlit_app.py", line 197, in main
    main_page()
  File "/home/levitsky/work/internal_ions/streamlit_app.py", line 47, in main_page
    tab1_main()
  File "/home/levitsky/work/internal_ions/tab1.py", line 66, in main
    st.session_state["identifications"] = read_identifications(identifications_file, identifications_file.name)
                                          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/levitsky/work/internal_ions/util/psmio.py", line 120, in read_identifications
    return read_other(filename, name, verbose)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/levitsky/work/internal_ions/util/psmio.py", line 90, in read_other
    scan_nr = int(psm["spectrum_id"])
              ^^^^^^^^^^^^^^^^^^^^^^^
ValueError: invalid literal for int() with base 10: '20100826_Velos2_AnMi_SA_HeLa_2Da.147.147.2'
```
Can we just not try to convert to it to integer? I suppose we would need to tweak `spectrumio.parse_scannr` so that it doesn't return integers either.

**Comment by michabirklbauer** [comment]
I think yes, we could just leave it as a string. 

The only problem currently is that we have an option to filter spectra by scan number for "Fraggraph" which expects the scan number to be an actual number because it checks for a min to max range (where min and max are filter options). I don't know if this would be still an option then - and if we actually need this filter?
(To be honest I still do not fully understand how we want to connect "Fraggraph" and basically everything that happens in tab 3 to the rest, so maybe we should just change it to string and worry about the problems it's causing along the way 😅 )

**Comment by michabirklbauer** [comment]
I think for the moment it's actually the best idea to just skip the manual spectrum / identifications reading because it's only used for "Fraggraph" which might still change down the line and then we would have to redo it anyway (especially because my codes looks really bad haha).
Just comment out or remove the following lines like in this commit: 585c9d4e2a2d3879ef44eca615096e1edcf914fa
